# Generated by Django 4.2.5 on 2023-11-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositions', '0002_remove_songs_comments_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='likes_users',
            field=models.ManyToManyField(default=0, related_name='liked_songs', to='compositions.userprofile'),
        ),
    ]
