# Generated by Django 4.2.5 on 2023-11-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='song',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='songs',
            name='comments_users',
        ),
        migrations.RemoveField(
            model_name='songs',
            name='likes_users',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
